package com.csye6225.fall2018.coursepractise.datamodel;

import java.util.List;
import javax.xml.bind.annotation.XmlRootElement;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="course")
public class Course {
	private String Id;
	private String courseId;
	private String taId;
	private String professorId;
	private List<Long> lectures;
	private long rosterId;
	private long boardId;
	private String department;
	private String notificationTopic;
	
	public Course() {
		
	}
	public Course(String courseId, String taId, String professorId, List<Long> lectures, long boardId, long rosterId, String department ) {
		this.setCourseId(courseId);
		this.setTaId(taId);
		this.setProfessorId(professorId);
		this.setLectures(lectures);
		this.setBoardId(boardId);
		this.setRosterId(rosterId);
		this.setDepartment(department);
		
	}
	
	@DynamoDBIndexHashKey(attributeName = "courseId",globalSecondaryIndexName = "courseId-index")
	public String getCourseId() {
		return courseId;
	}
	public void setCourseId(String courseId) {
		this.courseId = courseId;
	}
	
	@DynamoDBAttribute(attributeName = "taId")
	public String getTaId() {
		return taId;
	}
	public void setTaId(String taId) {
		this.taId = taId;
	}
	
	@DynamoDBAttribute(attributeName = "professorId")
	public String getProfessorId() {
		return professorId;
	}
	public void setProfessorId(String professorId) {
		this.professorId = professorId;
	}
	
	@DynamoDBAttribute(attributeName = "lectures")
	public List<Long> getLectures() {
		return lectures;
	}
	public void setLectures(List<Long> lectures) {
		this.lectures = lectures;
	}
	
	@DynamoDBAttribute(attributeName = "rosterId")
	public long getRosterId() {
		return rosterId;
	}
	public void setRosterId(long rosterId) {
		this.rosterId = rosterId;
	}
	
	@DynamoDBAttribute(attributeName = "boardId")
	public long getBoardId() {
		return boardId;
	}
	public void setBoardId(long boardId) {
		this.boardId = boardId;
	}
	
	@DynamoDBAttribute(attributeName = "department")
	public String getDepartment() {
		return department;
	}
	public void setDepartment(String department) {
		this.department = department;
	}
	
	@DynamoDBHashKey(attributeName = "Id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return Id;
	}
	public void setId(String id) {
		Id = id;
	}
	
	@DynamoDBAttribute(attributeName = "notificationTopic")
	public String getNotificationTopic() {
		return notificationTopic;
	}
	public void setNotificationTopic(String notificationTopic) {
		this.notificationTopic = notificationTopic;
	}

}
