package com.csye6225.fall2018.coursepractise.datamodel;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "courseBoard")
public class CourseBoard {
	
	private String Id;
	private long boardId;
	private String courseId;
	
	public CourseBoard() {
		
	}
	
	public CourseBoard(long boardId, String courseId) {
		this.setBoardId(boardId);
		this.setCourseId(courseId);
	}
	
	@DynamoDBIndexHashKey(attributeName = "boardId",globalSecondaryIndexName = "boardId-index")
	public long getBoardId() {
		return boardId;
	}

	public void setBoardId(long boardId) {
		this.boardId = boardId;
	}

	@DynamoDBAttribute(attributeName = "courseId")
	public String getCourseId() {
		return courseId;
	}

	public void setCourseId(String courseId) {
		this.courseId = courseId;
	}

	@DynamoDBHashKey(attributeName = "Id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return Id;
	}

	public void setId(String id) {
		Id = id;
	}
}
