package com.csye6225.fall2018.coursepractise.datamodel;

import java.util.List;
import javax.xml.bind.annotation.XmlRootElement;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="program")
public class Program {
	private String Id;
	private String programId;
	private String programName;
	private List<String> students;
	private List<String> courses;
	
	public Program() {
		
	}
	
	public Program(String programId,String programName, List<String> students, List<String> courses) {
		this.setProgramId(programId);
		this.setProgramName(programName);
		this.setStudents(students);
		this.setCourses(courses);
	}
	
	@DynamoDBHashKey(attributeName = "Id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return Id;
	}

	public void setId(String id) {
		Id = id;
	}

	@DynamoDBIndexHashKey(attributeName = "programId",globalSecondaryIndexName = "program Id-index")
	public String getProgramId() {
		return programId;
	}

	public void setProgramId(String programId) {
		this.programId = programId;
	}

	@DynamoDBAttribute(attributeName = "programName")
	public String getProgramName() {
		return programName;
	}

	public void setProgramName(String programName) {
		this.programName = programName;
	}

	@DynamoDBAttribute(attributeName = "students")
	public List<String> getStudents() {
		return students;
	}

	public void setStudents(List<String> students) {
		this.students = students;
	}

	@DynamoDBAttribute(attributeName = "courses")
	public List<String> getCourses() {
		return courses;
	}

	public void setCourses(List<String> courses) {
		this.courses = courses;
	}	
}
