package com.csye6225.fall2018.coursepractise.datamodel;

import java.util.List;
import javax.xml.bind.annotation.XmlRootElement;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="lecture")
public class Lecture {
	private String Id;
	private long lectureId;
	private String courseId;
	private List<String> notes;
	private List<String> materials;

	public Lecture() {
		
	}
	
	public Lecture(long lectureId, String courseId, List<String> notes, List<String> materials) {
		this.setLectureId(lectureId);
		this.setNotes(notes);
		this.setMaterials(materials);
		this.courseId = courseId;
	}

	@DynamoDBIndexHashKey(attributeName = "lectureId",globalSecondaryIndexName = "lectureId-index")
	public long getLectureId() {
		return lectureId;
	}

	public void setLectureId(long lectureId) {
		this.lectureId = lectureId;
	}

	@DynamoDBAttribute(attributeName = "notes")
	public List<String> getNotes() {
		return notes;
	}

	public void setNotes(List<String> notes) {
		this.notes = notes;
	}

	@DynamoDBAttribute(attributeName = "materials")
	public List<String> getMaterials() {
		return materials;
	}

	public void setMaterials(List<String> materials) {
		this.materials = materials;
	}

	@DynamoDBAttribute(attributeName = "courseId")
	public String getCourseId() {
		return courseId;
	}

	public void setCourseId(String courseId) {
		this.courseId = courseId;
	}

	@DynamoDBHashKey(attributeName = "Id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return Id;
	}

	public void setId(String id) {
		Id = id;
	}
}

